name: 'Build IBM release'

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: 'Make the Distribution Directory'
              run: |
                  mkdir  ibm-fortigate-terraform-deploy
            - name: 'Copy the files'
              run: |
                  cp *.tf *.conf LICENSE README.md ./ibm-fortigate-terraform-deploy/
            - name: 'Build the ZIP'
              run: |
                  tar -czf ibm-fortigate-terraform-deploy-singlevm.tar.gz ibm-fortigate-terraform-deploy/
            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.IBM_TOKEN }}'
                  automatic_release_tag: 'latest'
                  prerelease: false
                  title: 'ibm-fortigate-terraform-deploy-singlevm.'
                  files: |
                      ibm-fortigate-terraform-deploy-singlevm.tar.gz
